create schema cars;
SELECT*FROM CARS.CAR_DEKHO;
USE CARS;

-- READ CARS DATA --
select*FROM CAR_DEKHO;

-- TOTAL CARS:TO GET A COUNT OF TOTAL RECORDS --
select count(*)FROM CAR_DEKHO;

-- THE MANAGER ASKED THE EMPLOYEE HOW MANY CARS WILL BE AVAILABLE IN 2023? --
select COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2023;

-- THE MANAGER ASKED THE EMPLOYEE HOW MANY CARS IS AVAILABLE IN 2020,2021,2022 --
select COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2020;
select COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2021;
select COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2022;
 #OR
 SELECT count(*)FROM CAR_DEKHO WHERE YEAR IN (2020,2021,2022) group by YEAR;
 
 -- CLINT ASKED ME TO PRINT THE TOTAL OF ALL CARS BY YEAR : I DONT SEE ALL THE DETAILS --
 select YEAR, COUNT(*) FROM CAR_DEKHO group by YEAR;
 
 -- CLINT ASKED TO CAR DELAR AGENT HOW MANY DIESEL CARS WILL THERE BE IN 2020 --
 select COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2020 AND FUEL = 'DIESEL';
 
 -- CLINT REQUESTED A CAR DEALER AGENT HOW MANY PETROL CARS WILL THERE BE IN 2020 --
 SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2020 AND FUEL = 'PETROL' ;
 
 -- THE MANAGER TOLD THE EMPLOYEE TO GIVE A PRINT ALL THE FUEL CARS (PETROL,DIESELAND CNG) COME BY ALL YEAR --
 select YEAR, COUNT(*) FROM CAR_DEKHO WHERE FUEL = "PETROL"	group by YEAR;
 select YEAR, COUNT(*) FROM CAR_DEKHO WHERE FUEL = "DIESEL"	group by YEAR;
 select YEAR, COUNT(*) FROM CAR_DEKHO WHERE FUEL = "CNG"	group by YEAR;
 
 -- MANAGER SAID THERE WERE MORE THAN 100 CARS IN A GIVEN YAER ,WHICH YEAR HAD MORE THAN 100 CARS --
 SELECT YEAR,COUNT(*) FROM CAR_DEKHO GROUP BY YEAR HAVING COUNT(*)>100;
 SELECT YEAR,COUNT(*) FROM CAR_DEKHO GROUP BY YEAR HAVING COUNT(*)<50;
 
 -- THE MANAGER SAID TO THE EMPLOYEE ALL CARS COUNT DETAILS BETWEEN 2015 AND  2023 WE NEED THE COMPLETE LIST --
 SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR between 2015 AND 2023;
 
 -- THE MANAGER SAID TO THE EMPLOYEE ALL CARS DETAILS BETWEEN 2015 AND 2023 WE NEED COMPLETE LIST --
 SELECT * FROM CAR_DEKHO WHERE YEAR BETWEEN 2015 AND 2023;
 
 
 
 
 